'use strict';

exports.bookCategories = [
    {'value': 1, 'text': '现代言情'},
    {'value': 58, 'text': '现代言情'},
    {'value': 158, 'text': '现代言情'},
    {'value': 2, 'text': '古代言情'},
    {'value': 3, 'text': '玄幻奇幻'},
    {'value': 4, 'text': '武侠仙侠'},
    {'value': 5, 'text': '游戏竞技'},
    {'value': 6, 'text': '幻想言情'},
    {'value': 7, 'text': '历史军事'},
    {'value': 8, 'text': '灵异悬疑'},
    {'value': 9, 'text': '影视剧本'},
    {'value': 10, 'text': '科幻灵异'},
    {'value': 11, 'text': '文史传记'},
    {'value': 12, 'text': '穿越重生'},
    {'value': 14, 'text': '经管励志'},
    {'value': 15, 'text': '社科科普'},
    {'value': 16, 'text': '文学艺术'},
    {'value': 17, 'text': '都市校园'},
    {'value': 13, 'text': '都市校园'},
    {'value': 18, 'text': '教育教辅'},
    {'value': 161, 'text': '时尚生活'},
    {'value': 159, 'text': '畅销小说'}
];

exports.subjectBlockStyles = [
    {"id": 1, "name": "头条样式-图带标签", "contentType": 5},
    {"id": 2, "name": "标签-长方形", "contentType": 5},
    {"id": 3, "name": "标签-圆形", "contentType": 5},
    {"id": 4, "name": "banner图", "contentType": 2},
    {"id": 5, "name": "书单", "contentType": 1},
    {"id": 6, "name": "包月", "contentType": 11},
    {"id": 7, "name": "话题", "contentType": 6},
    {"id": 8, "name": "促销", "contentType": 10},
    {"id": 9, "name": "纯文字", "contentType": 5},
    {"id": 10, "name": "书-封面关键词", "contentType": 0},
    {"id": 11, "name": "书-封面评分", "contentType": 0},
    {"id": 12, "name": "书-封面数据", "contentType": 0},
    {"id": 13, "name": "书-关键词", "contentType": 0},
    {"id": 14, "name": "书-评分", "contentType": 0},
    {"id": 15, "name": "书-数据", "contentType": 0},
    {"id": 16, "name": "书-带促销信息", "contentType": 10},
    {"id": 17, "name": "书-单行简洁版", "contentType": 0},
    {"id": 18, "name": "九宫格", "contentType": 0},
    {"id": 24, "name": "专题名称标签", "contentType": 5},
    {"id": 25, "name": "分隔符[占位]", "contentType": 0},
    {"id": 26, "name": "九宫格-不带文字", "contentType": 0},
    {"id": 27, "name": "带颜色长标签", "contentType": 5},
    {"id": 28, "name": "带颜色圆形标签", "contentType": 5},
    {"id": 29, "name": "书-封面不可点关键词", "contentType": 0},
    {"id": 30, "name": "九宫格带分类", "contentType": 0},
    {"id": 31, "name": "书-榜单排行样式", "contentType": 0},
    {"id": 33, "name": "倒计时[占位]", "contentType": 30},
    {"id": 34, "name": "占位-默认书籍", "contentType": 0},
    {"id": 35, "name": "包月样式简洁版", "contentType": 11},
    {"id": 36, "name": "单个标签", "contentType": 5},
    {"id": 37, "name": "样式块", "contentType": 3},
    {"id": 38, "name": "包月-带购买或倒计时", "contentType": 11},
    {"id": 39, "name": "包月-全部列表样式", "contentType": 11},
    {"id": 40, "name": "头条样式2-大图3标签", "contentType": 5},
    {"id": 41, "name": "头条样式3-小图1标签", "contentType": 5},
    {"id": 42, "name": "头条样式4-大图2标签", "contentType": 5},
    {"id": 43, "name": "一小时追书榜-柱状图", "contentType": 0},
    {"id": 44, "name": "标题+说明", "contentType": 5},
    {"id": 45, "name": "主贴头条样式", "contentType": 5}
];
exports.dynamicTypes = [
    {"value": 0, "text": "没有"},
    {"value": 1, "text": "点击数"},
    {"value": 2, "text": "促销额外数据"},
    {"value": 3, "text": "订购数"},
    {"value": 4, "text": "书籍分类"},
    {"value": 5, "text": "书籍字数"},
    {"value": 6, "text": "书籍投票数"}
];
exports.bookFormats = [
    {'value': '0', 'text': 'txt'},
    {'value': '1', 'text': 'epub'}
]
exports.linkTagTargets = [
    {'value': 0, 'text': '书籍'},
    {'value': -1, 'text': '标准书籍'},
    {'value': 1, 'text': '书单'},
    {'value': 4, 'text': '独立专题'},
    {'value': 7, 'text': '综合推荐'},
    {'value': 10, 'text': '促销书籍'},
    {'value': 11, 'text': '包月包'},
    {'value': 12, 'text': '任务'},
    {'value': 13, 'text': '榜单'},
    {'value': 14, 'text': '分类'},
    {'value': 15, 'text': '促销折扣'},
    {'value': 17, 'text': '内部界面'},
    {'value': 22, 'text': 'APK下载'},
    {'value': 23, 'text': '网页'},
    {'value': 25, 'text': '内部网页'},
    {'value': 26, 'text': '打开应用市场'},
    {'value': 30, 'text': '纯文字/图片'},
    {'value': 32, 'text': '促销频道'},
    {'value': 33, 'text': '书评频道'},
    {'value': 34, 'text': '求书频道'},
    {'value': 35, 'text': '分享书籍频道'},
    {'value': 36, 'text': '包月频道'},
    {'value': 39, 'text': '导航栏'},
    {'value': 40, 'text': '导航栏内容项'},
    {'value': 41, 'text': '书吧'},
    {'value': 42, 'text': '主贴'}
];
exports.bannerTargets = [
    {'value': 1, 'text': '书籍'},
    {'value': 2, 'text': 'APK'},
    {'value': 3, 'text': '网页'},
    {'value': 4, 'text': '书单'},
    {'value': 5, 'text': '内部网页'},
    {'value': 8, 'text': '综合推荐'},
    {'value': 9, 'text': '纯图片显示'},
    {'value': 10, 'text': '促销折扣'},
    {'value': 11, 'text': '包月包'},
    {'value': 17, 'text': '内部界面'},
    {'value': 26, 'text': '打开应用市场'},
    {'value': 104, 'text': '独立专题'},
    {'value': 106, 'text': '话题'},
    {'value': 108, 'text': '书评'},
    {'value': 109, 'text': '求书'},
    {'value': 112, 'text': '任务'},
    {'value': 113, 'text': '榜单'},
    {'value': 114, 'text': '分类'},
    {'value': 115, 'text': '折扣书籍'},
    {'value': 132, 'text': '促销频道'},
    {'value': 133, 'text': '书评频道'},
    {'value': 134, 'text': '求书频道'},
    {'value': 135, 'text': '分享书籍频道'},
    {'value': 39, 'text': '导航栏'},
    {'value': 40, 'text': '导航栏内容项'},
    {'value': 41, 'text': '书吧'},
    {'value': 42, 'text': '主贴'}
]